image: roadiz/php73-runner

stages:
  - test
  - build
  - deploy

variables:
  # Timezone will be used both for system and php date.timezone php.ini value
  TIMEZONE: "Europe/Paris"
  # SENTRY_URL: "https://sentry.yourdomain.com/api/hooks/release/builtin/x/xxxxx/"

example_test:
  stage: test
  image: roadiz/php73-runner
  only:
    - develop
    - tags
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
  script:
    - composer install --no-scripts
    - vendor/bin/phpcs

example_build:
  stage: build
  image: roadiz/php73-runner
  only:
    - develop
    - tags
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - themes/BaseTheme/node_modules/
      - vendor/
  artifacts:
    expire_in: 1 hour
    paths:
      - vendor/
      # Replace with your own theme path
      - themes/BaseTheme/
      # Keep themes assets to include them in docker image
      - web/themes/
  before_script:
    # Paste the PRIVATE key into a gitlab variable.
    # Pay attention to the linebreak at the end when pasting
    # Composer private key is required if you need private dependencies.
    # **Uncomment only if using private composer packages**
    #- mkdir -p ~/.ssh
    #- echo "$COMPOSER_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    #- chmod 600 ~/.ssh/id_rsa
    #- eval "$(ssh-agent -s)"
    #- ssh-add ~/.ssh/id_rsa
    ## Use your Gitlab instance URL
    #- ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
  script:
    # Replace with your own theme path
    - cd themes/BaseTheme
    # If you’re using Sass, install it locally
    # https://github.com/sass/node-sass/issues/1980
    # - yarn add node-sass
    - yarn install
    # Using Yarn with yarn.lock
    #- yarn install --pure-lockfile
    - yarn run build
    - cd ../../
    # DO NOT USE --classmap-authoritative as we are going to generate nsentities on the go…
    - composer install --no-dev --optimize-autoloader --apcu-autoloader --no-scripts
    - composer run-script post-install-cmd
    # Create hard copies of theme assets
    - composer run-script pre-docker
    - rm -rf web/dev.php
    - rm -rf web/install.php

#
# Build App docker image with vendor and built assets
# included. You must configure your Gitlab Runner to
# support Docker-in-docker commands.
#
example_docker:
  stage: deploy
  image: docker:git
  # Create a docker image only when a new tag is pushed
  only:
    - tags
  services:
    - docker:dind
  when: on_success
  dependencies:
    - example_build
  before_script:
    # Need curl for pushing release to Sentry
    - apk add curl
  script:
    # Connect to your Gitlab Registry
    - "echo \"Registry image: ${CI_REGISTRY_IMAGE} for tag ${CI_COMMIT_TAG}\""
    - "docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}"
    # App image build
    - "docker build -t ${CI_REGISTRY_IMAGE} ."
    - "docker tag ${CI_REGISTRY_IMAGE} ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    - "docker push ${CI_REGISTRY_IMAGE}:latest"
    - "docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    # Create Release on your app on Sentry
    # - "curl ${SENTRY_URL} -X POST -H \"Content-Type: application/json\" -d \"{\\\"version\\\": \\\"${CI_COMMIT_TAG}\\\"}\""


