version: '3'
services:
    db:
        image: mysql:5.7
        volumes:
            - "./.data/db:/var/lib/mysql:delegated"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    app:
        build:
            context: ./docker/php74-nginx-alpine
            args:
                USER_UID: ${USER_UID}
        ports:
            - 8088:80
        depends_on:
            - db
            - solr
        volumes:
            - ./:/var/www/html:consistent
        environment:
            USE_APP_CACHE: ${USE_APP_CACHE}
            USER_UID: ${USER_UID}
    solr:
         image: solr
         ports:
             - "8983/tcp"
         volumes:
             - "./.data/solr:/opt/solr/server/solr/mycores:delegated"
         entrypoint:
             - docker-entrypoint.sh
             - solr-precreate
             - roadiz

