version: '3'
services:
    db:
        build:
            # Custom image for file permissions
            context: ./docker/mysql
            args:
                USER_UID: ${USER_UID}
        image: mysql:5.7
        volumes:
            - "./.data/db:/var/lib/mysql:delegated"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PMA_PORT}:80/tcp
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - frontproxynet
            - default
        labels:
            # Replace example_pma by your service name
            - "traefik.enable=true"
            - "traefik.http.services.example_pma.loadbalancer.server.scheme=http"
            - "traefik.http.services.example_pma.loadbalancer.server.port=80"
            - "traefik.http.services.example_pma.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.example_pma.entrypoints=http"
            - "traefik.http.routers.example_pma.rule=Host(${HOSTNAME_PMA)"
            - "traefik.http.routers.example_pma.service=example_pma"

    app:
        build:
            context: ./docker/php74-nginx-alpine
            args:
                USER_UID: ${USER_UID}
        ports:
            - ${APP_PORT}:80/tcp
        depends_on:
            - db
            - solr
        volumes:
            - ${ROADIZ_APP_PATH}:/var/www/html:cached
        networks:
            - frontproxynet
            - default
        environment:
            USE_APP_CACHE: ${USE_APP_CACHE}
            USER_UID: ${USER_UID}
            DEFAULT_GATEWAY: ${DEFAULT_GATEWAY}
            BLACKFIRE_LOG_LEVEL: ${BLACKFIRE_LOG_LEVEL}
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
            BLACKFIRE_ENDPOINT: "https://blackfire.io"
        labels:
            # Replace example by your service name
            - "traefik.enable=true"
            - "traefik.http.services.example.loadbalancer.server.scheme=http"
            - "traefik.http.services.example.loadbalancer.server.port=80"
            - "traefik.http.services.example.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.example.entrypoints=http"
            - "traefik.http.routers.example.rule=Host(${HOSTNAME})"
            - "traefik.http.routers.example.service=example"

    solr:
        build:
            # Custom image for file permissions
            context: ./docker/solr
            args:
                USER_UID: ${USER_UID}
        image: solr:8-slim
        ports:
            - "${SOLR_PORT}:8983/tcp"
        volumes:
            - "./.data/solr:/var/solr:delegated"
        environment:
            SOLR_UID: ${USER_UID}
            SOLR_GID: ${USER_UID}
        command:
            - solr-precreate
            - roadiz
        networks:
            - frontproxynet
            - default
        labels:
            # Replace example_solr by your service name
            - "traefik.enable=true"
            - "traefik.http.services.example_solr.loadbalancer.server.scheme=http"
            - "traefik.http.services.example_solr.loadbalancer.server.port=8983"
            - "traefik.http.services.example_solr.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.example_solr.entrypoints=http"
            - "traefik.http.routers.example_solr.rule=Host(${HOSTNAME_SOLR})"
            - "traefik.http.routers.example_solr.service=example_solr"

    mailer:
        image: mailhog/mailhog
        ports:
            - ${MAILER_PORT}:8025/tcp
        networks:
            - frontproxynet
            - default
        labels:
            # Replace example_mailer by your service name
            - "traefik.enable=true"
            - "traefik.http.services.example_mailer.loadbalancer.server.scheme=http"
            - "traefik.http.services.example_mailer.loadbalancer.server.port=8025"
            - "traefik.http.services.example_mailer.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.example_mailer.entrypoints=http"
            - "traefik.http.routers.example_mailer.rule=Host(${HOSTNAME_MAILER})"
            - "traefik.http.routers.example_mailer.service=example_mailer"

    blackfire:
        image: blackfire/blackfire
        environment:
            # Exposes BLACKFIRE_* environment variables from the host
            BLACKFIRE_LOG_LEVEL: ${BLACKFIRE_LOG_LEVEL}
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}

    varnish:
        build:
            context: ./docker/varnish
        tmpfs: /usr/local/var/varnish:exec
        depends_on:
            - app
        links:
            - app:app
        ports:
            - ${VARNISH_PORT}:80/tcp
        networks:
            - frontproxynet
            - default
        labels:
            # Replace example by your service name
            - "traefik.enable=true"
            - "traefik.http.services.example_varnish.loadbalancer.server.scheme=http"
            - "traefik.http.services.example_varnish.loadbalancer.server.port=80"
            - "traefik.http.services.example_varnish.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.example_varnish.entrypoints=http"
            - "traefik.http.routers.example_varnish.rule=Host(${HOSTNAME_VARNISH})"
            - "traefik.http.routers.example_varnish.service=example_varnish"

networks:
    frontproxynet:
        external: true
    default:
        ipam:
            driver: default
            config:
                -   subnet: ${DEFAULT_GATEWAY}/16
