version: '2'
services:
    db:
        image: mysql:5.6
        volumes:
            - "./.data/db:/var/lib/mysql:cached"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    app:
        build: ./docker/php73-nginx-alpine
        ports:
            - 80:80
        depends_on:
            - db
            - solr
        volumes:
            - ${ROADIZ_APP_PATH}:/var/www/html
        environment:
            USE_APP_CACHE: ${USE_APP_CACHE}
    solr:
         image: solr
         ports:
             - "8983:8983"
         volumes:
             - "./.data/solr:/opt/solr/server/solr/mycores:cached"
         entrypoint:
             - docker-entrypoint.sh
             - solr-precreate
             - roadiz
