---
##
## Docker DEV stack config example
##
appNamespace: "chooseAnUniqueNameForYourApp"
timezone: "Europe/Paris"
doctrine:
    driver: "pdo_mysql"
    host: "db"
    user: "roadiz"
    password: "roadiz"
    dbname: "roadiz"
    # "utf8mb4" charset requires at least mysql 5.7
    # due to large index requirement.
    # otherwise change it to "utf8"
    charset: utf8mb4
    default_table_options:
        charset: utf8mb4
        collate: utf8mb4_unicode_ci
# Register here your themes…
themes: []
# http://symfony.com/doc/current/reference/configuration/doctrine.html#caching-drivers
# If null or empty, Roadiz will use ArrayCache
cacheDriver:
    type: apcu
    host: ~
    port: ~
security:
    secret: "change#this#secret#very#important"
    session_name: roadiz_token
    session_cookie_secure: false
    session_cookie_httponly: true
    # Change default password algorithm from sha512 to argon2i
    algorithm: argon2i
mailer:
    type: smtp
    host: "mailer"
    port: 1025
    encryption: false
    username: ""
    password: ""
# Doctrine entities search paths
# Append yours here if you want to create custom
# entities in your theme. Path must be relative to
# root dir (app/)
entities:
    - "../vendor/roadiz/roadiz/src/Roadiz/Core/Entities"
    - "../vendor/roadiz/models/src/Roadiz/Core/AbstractEntities"
    - "gen-src/GeneratedNodeSources"
# Lifetime of remember-me cookie in seconds (30 days)
rememberMeLifetime: 2592000
# Add service providers here OR add them directly in AppKernel::register
additionalServiceProviders: []
additionalCommands: []
# Image intervention and Intervention Request
# settings for generating image on the fly
assetsProcessing:
    # gd or imagick (gd does not support TIFF and PSD formats)
    driver: gd
    defaultQuality: 95
    # pixel size limit () after roadiz
    # should create a smaller copy.
    maxPixelSize: 2500
    jpegoptimPath: /usr/bin/jpegoptim
    pngquantPath: /usr/bin/pngquant
    subscribers: []
#
# Solr endpoint example
#
solr:
    endpoint:
        localhost:
            host: "solr"
            port: "8983"
            path: "/"
            core: "roadiz"
            timeout: 3
            username: ""
            password: ""

#
# Reverse proxy invalidation
#
#reverseProxyCache:
#    frontend:
#        localhost:
#            host: localhost
#            domainName: myapp.test
#
#        external:
#            host: varnish
#            domainName: myapp.test

